[package]
name = "entity-core"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
sqlx = { version = "0.8", features = [ "mysql", "runtime-tokio", "tls-rustls-ring-native-roots" ] }
tokio = { version = "1.46.1", features = ["full"] }
